import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CardContentService {

  cards = [
    {title: 'Serj', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio ipsam quaerat corrupti magnam iure quos soluta dolores amet earum officiis assumenda velit sunt, dignissimos voluptatem vero, fugit vel? Earum fugiat deserunt quisquam architecto, aut ipsam. Dolore in reiciendis minus error, odit esse ullam exercitationem alias a culpa! Minima, modi accusamus ex commodi dicta in id voluptatum expedita sequi facere laudantium, odio impedit! Aut eos nulla consequatur tempora earum necessitatibus doloremque aliquam similique voluptate at neque, veritatis esse quia maiores libero, amet beatae ullam quae vitae autem animi pariatur aspernatur repellendus. Minima soluta eaque temporibus, aliquam magni quaerat ex architecto necessitatibus natus voluptatum sapiente voluptas fugit hic velit ipsum, inventore ad tempore quod libero veritatis excepturi dolores nobis. Suscipit neque voluptas facere sapiente labore. Facere deleniti porro repudiandae minima maxime sint assumenda eveniet omnis, voluptates sequi ipsa non itaque provident ut quis enim distinctio nihil possimus molestiae sapiente fugit. Laboriosam quisquam quaerat error, ipsum recusandae incidunt, eaque nostrum esse autem optio atque illo delectus. Voluptate mollitia error necessitatibus quibusdam fugit laudantium repellat omnis sed, velit soluta enim amet dolor veritatis perferendis deserunt repudiandae reprehenderit maxime praesentium. Temporibus natus excepturi suscipit dolorem fugit, unde assumenda numquam, quisquam, vero repudiandae obcaecati perferendis asperiores.', imgPath: '../../../assets/images/news.jpg', date: '29.01.2018'},
    {title: 'Conserj', description: 'Далеко-далеко за словесными горами в стране гласных и согласных живут, рыбные тексты. Своих оксмокс большого не своего, заглавных вопроса прямо это но великий продолжил запятых даже вскоре рукописи несколько ручеек родного последний толку дал вершину. Ее пояс образ предупредила о текста своего, знаках рекламных которой текст обеспечивает ему все мир приставка первую даже имеет города, себя деревни однажды то последний предупреждал! Вскоре, послушавшись что напоивший но, обеспечивает предупредила деревни жизни текст, инициал подзаголовок ему предложения заголовок. Заманивший великий деревни, то ведущими, выйти текстами проектах даль ipsum страна, предупредила подпоясал эта о вершину. Возвращайся необходимыми взгляд пояс заглавных жаренные реторический составитель, своего дал напоивший выйти вопрос взобравшись. Своего возвращайся страна свое повстречался, точках единственное подзаголовок путь моей оксмокс взобравшись по всей даль напоивший щеке вопрос решила подпоясал меня которой деревни. Что вдали оксмокс меня продолжил. Предупреждал, заголовок рот! Букв текстами, снова до, собрал пор он силуэт, свое рот предупреждал над скатился но вопроса. Страна, переулка пор проектах своих предложения журчит запятых всеми все прямо повстречался, она над имени вскоре большой! Сбить пунктуация запятых прямо буквенных он власти переулка букв реторический грустный! Вскоре переулка свое которое его курсивных маленькая имеет собрал, необходимыми ее предложения образ даже, по всей которой. Агентство рукописи ее пунктуация рыбными живет всеми!', imgPath: '../../../assets/images/news.jpg', date: '12.02.2018'},
    {title: 'Top author', description: 'Mujer uno dolor más de, poder mismo si. O paloma, dolores pillo materialidad voluntad, culpa corrupto litro repelente comodidad dignísimo mayores chicharra triste abogada almácigo cábala temporal obcecado apéndice refugiado arquitecto. Laudo olvido temporal voluntad vos mirar, magma pan entero paño letra aparte paloma, conejo, mínima asunción ataque. Quindío alias tasmania modo fotografía. Afortunado fotografía auto triste manantial sapiencia, alias, distinción torre ataque mirar dolor laboral crepúsculo voluntad ex resiliencia, mayores namibia? Repeler repugnante consecuencia, marejada tasmania ataque ex laboral, casi necesariamente montaña verdades nihilista, mula inventor! Demás mula sintió, corporal soluciones auto y mayores cosas namibia, cuórum odio, débito paria total lejos consecuencia columna. Velo distinción crepúsculo cuórum? Repelente sed reincidente o olvido molde crepúsculo paño alias. Arquitecto laboral mosca alias yugo propósito repelente cábala dignísimo facilismo a natividad animal paria débito volutas encefalograma, león fotografía rayo molestias abadía! Pan sed presentación impedimento paria columna computador ley tenedor nihilista. Nihilista remo belleza perspicacia cosas paciencia comodidad total analfabeto marejada consecuencia dulce placenta nascimiento paloma molestias menos, inmune, mínima, necesariamente pan. Refugiado planeador pócima, lejos rayo alias menos obcecado verdades alma yugo ataque anemia fuga molde laboriosamente mula, cosas almácigo y natividad comodidad, como preferencia fantasía ex fugacidad? Placenta, ovni.', imgPath: '../../../assets/images/news.jpg', date: '07.05.2018'}
  ];

  constructor() { }
}
